[package]
name = "bpftop"
version = "0.2.1"
edition = "2021"

[dependencies]
libbpf-rs = "0.22.1"
libbpf-sys = "1.3.0"
crossterm = "0.27.0"
anyhow = "1.0.80"
ratatui = { version = "0.26.1", default-features = false, features = ['crossterm'] }
nix = "0.27.1"
circular-buffer = "0.1.6"